# Generated by Django 3.2.16 on 2024-04-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
