# Generated by Django 3.2.16 on 2024-04-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='test_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.testset'),
            preserve_default=False,
        ),
    ]
