# Generated by Django 3.2.16 on 2024-04-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_test_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.testset'),
        ),
    ]
